import { sql } from 'drizzle-orm';
import {
    index,
    integer,
    primaryKey,
    sqliteTable,
    text,
    uniqueIndex,
} from 'drizzle-orm/sqlite-core';

const nowMs = sql`(cast(unixepoch('subsecond') * 1000 as integer))`;

/* ------------------------------------------------------------------ */
/* better-auth core tables (generated by @better-auth/cli, kept in sync) */
/* ------------------------------------------------------------------ */

export const user = sqliteTable('user', {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    email: text('email').notNull().unique(),
    emailVerified: integer('email_verified', { mode: 'boolean' }).default(false).notNull(),
    image: text('image'),
    /* better-auth admin plugin fields */
    role: text('role'),
    banned: integer('banned', { mode: 'boolean' }).default(false),
    banReason: text('ban_reason'),
    banExpires: integer('ban_expires', { mode: 'timestamp_ms' }),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).default(nowMs).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
        .default(nowMs)
        .$onUpdate(() => new Date())
        .notNull(),
});

export const session = sqliteTable(
    'session',
    {
        id: text('id').primaryKey(),
        expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
        token: text('token').notNull().unique(),
        createdAt: integer('created_at', { mode: 'timestamp_ms' }).default(nowMs).notNull(),
        updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
            .$onUpdate(() => new Date())
            .notNull(),
        ipAddress: text('ip_address'),
        userAgent: text('user_agent'),
        userId: text('user_id')
            .notNull()
            .references(() => user.id, { onDelete: 'cascade' }),
        impersonatedBy: text('impersonated_by'),
    },
    table => [index('session_userId_idx').on(table.userId)]
);

export const account = sqliteTable(
    'account',
    {
        id: text('id').primaryKey(),
        accountId: text('account_id').notNull(),
        providerId: text('provider_id').notNull(),
        issuer: text('issuer').notNull(),
        userId: text('user_id')
            .notNull()
            .references(() => user.id, { onDelete: 'cascade' }),
        accessToken: text('access_token'),
        refreshToken: text('refresh_token'),
        idToken: text('id_token'),
        accessTokenExpiresAt: integer('access_token_expires_at', { mode: 'timestamp_ms' }),
        refreshTokenExpiresAt: integer('refresh_token_expires_at', { mode: 'timestamp_ms' }),
        scope: text('scope'),
        password: text('password'),
        createdAt: integer('created_at', { mode: 'timestamp_ms' }).default(nowMs).notNull(),
        updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
            .$onUpdate(() => new Date())
            .notNull(),
    },
    table => [index('account_userId_idx').on(table.userId)]
);

export const verification = sqliteTable(
    'verification',
    {
        id: text('id').primaryKey(),
        identifier: text('identifier').notNull(),
        value: text('value').notNull(),
        expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
        createdAt: integer('created_at', { mode: 'timestamp_ms' }).default(nowMs).notNull(),
        updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
            .default(nowMs)
            .$onUpdate(() => new Date())
            .notNull(),
    },
    table => [index('verification_identifier_idx').on(table.identifier)]
);

/* ------------------------------------------------------------------ */
/* Content                                                             */
/* ------------------------------------------------------------------ */

export const ENTRY_KINDS = ['remedy', 'tip', 'recipe', 'article'] as const;
export type EntryKind = (typeof ENTRY_KINDS)[number];

export const ENTRY_STATUSES = ['draft', 'published'] as const;
export type EntryStatus = (typeof ENTRY_STATUSES)[number];

export type Ingredient = {
    name: string;
    quantity?: string;
};

export const entries = sqliteTable(
    'entries',
    {
        id: text('id').primaryKey(),
        slug: text('slug').notNull(),
        kind: text('kind', { enum: ENTRY_KINDS }).notNull(),
        status: text('status', { enum: ENTRY_STATUSES }).notNull().default('draft'),
        title: text('title').notNull(),
        /** The complaint a remedy treats, the habit a tip builds, or the occasion a recipe suits. */
        useFor: text('use_for'),
        summary: text('summary').notNull(),
        /** Author's notes as GitHub-flavoured Markdown (the source of truth). */
        body: text('body').notNull().default(''),
        /** Sanitized HTML rendered from `body` when the entry is saved. */
        bodyHtml: text('body_html').notNull().default(''),
        ingredients: text('ingredients', { mode: 'json' })
            .$type<Ingredient[]>()
            .notNull()
            .default(sql`'[]'`),
        steps: text('steps', { mode: 'json' })
            .$type<string[]>()
            .notNull()
            .default(sql`'[]'`),
        tags: text('tags', { mode: 'json' })
            .$type<string[]>()
            .notNull()
            .default(sql`'[]'`),
        /** Health entries: when to stop and see a doctor. */
        caution: text('caution'),
        prepMinutes: integer('prep_minutes'),
        cookMinutes: integer('cook_minutes'),
        servings: text('servings'),
        coverImage: text('cover_image'),
        authorId: text('author_id').references(() => user.id, { onDelete: 'set null' }),
        publishedAt: integer('published_at', { mode: 'timestamp_ms' }),
        createdAt: integer('created_at', { mode: 'timestamp_ms' }).default(nowMs).notNull(),
        updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
            .default(nowMs)
            .$onUpdate(() => new Date())
            .notNull(),
    },
    table => [
        uniqueIndex('entries_slug_idx').on(table.slug),
        index('entries_kind_status_idx').on(table.kind, table.status, table.publishedAt),
    ]
);

export type Entry = typeof entries.$inferSelect;
export type NewEntry = typeof entries.$inferInsert;

/* ------------------------------------------------------------------ */
/* Readers: likes and comments                                         */
/* ------------------------------------------------------------------ */

export const likes = sqliteTable(
    'likes',
    {
        entryId: text('entry_id')
            .notNull()
            .references(() => entries.id, { onDelete: 'cascade' }),
        userId: text('user_id')
            .notNull()
            .references(() => user.id, { onDelete: 'cascade' }),
        createdAt: integer('created_at', { mode: 'timestamp_ms' }).default(nowMs).notNull(),
    },
    table => [
        primaryKey({ columns: [table.entryId, table.userId] }),
        index('likes_entry_idx').on(table.entryId),
    ]
);

export const comments = sqliteTable(
    'comments',
    {
        id: text('id').primaryKey(),
        entryId: text('entry_id')
            .notNull()
            .references(() => entries.id, { onDelete: 'cascade' }),
        userId: text('user_id')
            .notNull()
            .references(() => user.id, { onDelete: 'cascade' }),
        body: text('body').notNull(),
        /** Top-level comments have no parent; replies point at a top-level comment. */
        parentId: text('parent_id'),
        createdAt: integer('created_at', { mode: 'timestamp_ms' }).default(nowMs).notNull(),
        updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
            .default(nowMs)
            .$onUpdate(() => new Date())
            .notNull(),
    },
    table => [
        index('comments_entry_idx').on(table.entryId, table.createdAt),
        index('comments_parent_idx').on(table.parentId),
    ]
);

export const commentLikes = sqliteTable(
    'comment_likes',
    {
        commentId: text('comment_id')
            .notNull()
            .references(() => comments.id, { onDelete: 'cascade' }),
        userId: text('user_id')
            .notNull()
            .references(() => user.id, { onDelete: 'cascade' }),
        createdAt: integer('created_at', { mode: 'timestamp_ms' }).default(nowMs).notNull(),
    },
    table => [
        primaryKey({ columns: [table.commentId, table.userId] }),
        index('comment_likes_comment_idx').on(table.commentId),
    ]
);

export type Comment = typeof comments.$inferSelect;
